// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_9dscc-yIllzvwkzPTtcCVvofQebHXbU',
    appId: '1:756208434488:web:a979fd59474286f8e595cd',
    messagingSenderId: '756208434488',
    projectId: 'shop-app-customer',
    authDomain: 'shop-app-customer.firebaseapp.com',
    storageBucket: 'shop-app-customer.appspot.com',
    measurementId: 'G-LPNR981T86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8A8wGA7_tOlXU4_dyWrKVSxlnrXUl-_s',
    appId: '1:756208434488:android:bfcdd5c2e5752653e595cd',
    messagingSenderId: '756208434488',
    projectId: 'shop-app-customer',
    storageBucket: 'shop-app-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_1PBrYFhPmARGuJU19t3ZhCOpVuq9Ry8',
    appId: '1:756208434488:ios:87dfcd80be96d589e595cd',
    messagingSenderId: '756208434488',
    projectId: 'shop-app-customer',
    storageBucket: 'shop-app-customer.appspot.com',
    iosBundleId: 'com.example.ecommerceShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_1PBrYFhPmARGuJU19t3ZhCOpVuq9Ry8',
    appId: '1:756208434488:ios:3ffd16444770519be595cd',
    messagingSenderId: '756208434488',
    projectId: 'shop-app-customer',
    storageBucket: 'shop-app-customer.appspot.com',
    iosBundleId: 'com.example.ecommerceShopApp.RunnerTests',
  );
}
